### ISSUE TITLE
Array flags are incorrectly parsed when using tsx

### ISSUE THREAD

**Issue by so1ve** [privatenumber/type-flag#22]
```ts
// foo.ts
import { typeFlag } from "type-flag";

const parsed = typeFlag({
  verbose: {
    type: [Boolean],
    alias: "v",
  },
});

console.log(parsed.flags.verbose.length);
```

Call `tsx foo.ts -vvv` prints 9, but if we call `npx tsc foo.ts` first and then use `node foo.js -vvv`, this error will not occur.

**Comment by so1ve** [comment]
```ts
console.log(process.argv.slice(2));

// using tsx -> [ '-vvv', '-vvv', '-vvv' ]
// using node -> [ '-vvv' ]
```
It seems that `-vvv` is repeated three times. Maybe it's a tsx issue?

**Comment by privatenumber** [comment]
Works for me with the latest versions of both.

If the issue still persists after upgrading, please provide a reproduction repo.

**Comment by so1ve** [comment]
Oh, and upgrading the tsx to the latest version fixed it... weird
