### ISSUE TITLE
support adding description to flags

### ISSUE THREAD

**Issue by KraXen72** [privatenumber/type-flag#24]
### Feature request

i would like to add a short description to a flag that shows up when user runs `--help`

### Motivations

sometimes the flag name is not enough to explain it's specifics

### Alternatives

comments in code above the flag

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
This is supported in cleye which uses type-flag to add --help support

https://github.com/privatenumber/cleye
